apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: vishal-chatapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: chatapp-backend
          image: vishal2728/vishal-backend:alpine
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: development
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: JWT_SECRET
            - name: PORT
              value: "5002"
